// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeCleanupOnSave
{
    internal sealed partial class Vsix
    {
        public const string Id = "66985471-b701-4851-a2d7-5a8bdce1e694";
        public const string Name = "Code Cleanup On Save";
        public const string Description = @"Automatically run one of the Code Clean profiles when saving the document. This ensures your code is always formatted correctly and follows your coding style conventions.";
        public const string Language = "en-US";
        public const string Version = "1.0.999";
        public const string Author = "Mads Kristensen";
        public const string Tags = "cleanup, formatting";
    }
}
