// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeCleanupOnSave
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCodeCleanupOnSavePackageString = "aee4d337-3c9a-4f9b-86ae-6dd7bd751bd5";
        public static Guid guidCodeCleanupOnSavePackage = new Guid(guidCodeCleanupOnSavePackageString);

        public const string guidValidFileString = "e53facf8-0840-4d99-bd57-fafcb7de25e4";
        public static Guid guidValidFile = new Guid(guidValidFileString);

        public const string guidCodeCleanupOnSavePackageCmdSetString = "d8b9208d-7e71-4fbe-9c53-6950c7c5679b";
        public static Guid guidCodeCleanupOnSavePackageCmdSet = new Guid(guidCodeCleanupOnSavePackageCmdSetString);

        public const string guidEditorCommandsString = "160961b3-909d-4b28-9353-a1bef587b4a6";
        public static Guid guidEditorCommands = new Guid(guidEditorCommandsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int RunOnSave = 0x0100;
        public const int IDG_CTX_CODECLEANUP_PROFILES = 0x0025;
    }
}